export interface VehicleDisplayDriverProfile { name: string; plate: string; vehicleModel: string; photoUrl: string | null }
export interface VehicleDisplayTripSummary { id: string; bookerName: string; fare: number; currency: string; paymentMethod: 'cash' | 'qris' | 'ewallet'; paymentStatus: string }
export interface VehicleDisplaySessionResponse { pairingId: string; vehicleId: string; vehicleLabel: string; pairedAt: string; driver: VehicleDisplayDriverProfile; activeTrip: VehicleDisplayTripSummary | null }
export interface VehicleDisplayPairingRequestResponse { requestId: string; pairingCode: string; sessionToken: string; expiresAt: string }
export interface VehicleDisplayPairingRequestStatusResponse { status: 'pending' | 'claimed' | 'expired' | 'revoked' | 'invalid'; pairingId?: string; vehicleId?: string; vehicleLabel?: string; pairedAt?: string }
export interface VehicleDisplayCurrent { driver: VehicleDisplayDriverProfile; order: { id: string; service: 'ride' | 'delivery'; status: 'requested' | 'searching' | 'assigned' | 'arriving' | 'in_progress' | 'completed' | 'cancelled'; pickup: { address: string }; destination: { address: string }; distance: number; eta: number; price: number; payment: 'cash' | 'qris' | 'ewallet' } | null }
type ApiRequestError = Error & { status?: number; response?: { status?: number }; data?: unknown };
const API_BASE = (import.meta.env.VITE_API_BASE_URL ?? '').replace(/\/+$/, '');
function resolveUrl(input: RequestInfo | URL): string { const raw = input instanceof Request ? input.url : String(input); if (/^https?:\/\//i.test(raw)) return raw; return `${API_BASE}${raw.startsWith('/') ? raw : `/${raw}`}`; }
async function makeApiError(response: Response): Promise<ApiRequestError> { let data: unknown = null; try { data = await response.clone().json(); } catch { try { data = await response.text(); } catch { data = null; } } const record = data && typeof data === 'object' ? data as Record<string, unknown> : null; const message = typeof record?.error === 'string' ? record.error : typeof record?.message === 'string' ? record.message : `Request failed (${response.status})`; const error = new Error(message) as ApiRequestError; error.status = response.status; error.response = { status: response.status }; error.data = data; return error; }
export async function customFetchRaw(input: RequestInfo | URL, options: RequestInit = {}): Promise<Response> { const response = await fetch(resolveUrl(input), options); if (!response.ok) throw await makeApiError(response); return response; }
async function requestJson<T>(path: string, options: RequestInit = {}): Promise<T> { const response = await customFetchRaw(path, { headers: { Accept: 'application/json', ...Object.fromEntries(new Headers(options.headers).entries()) }, ...options }); return await response.json() as T; }
export function createVehicleDisplayPairingRequest(options: RequestInit = {}): Promise<VehicleDisplayPairingRequestResponse> { return requestJson('/api/vehicle-display/pairing-requests', { ...options, method: 'POST' }); }
export function getVehicleDisplaySession(options: RequestInit = {}): Promise<VehicleDisplaySessionResponse> { return requestJson('/api/vehicle-display/session', options); }
export function getVehicleDisplayPairingRequestStatus(requestId: string, options: RequestInit = {}): Promise<VehicleDisplayPairingRequestStatusResponse> { return requestJson(`/api/vehicle-display/pairing-requests/${encodeURIComponent(requestId)}`, options); }
export function unpairVehicleDisplay(body: { pairingId: string }, options: RequestInit = {}): Promise<{ revoked: boolean }> { const headers = new Headers(options.headers); headers.set('content-type', 'application/json'); return requestJson('/api/vehicle-display/unpair', { ...options, method: 'POST', headers, body: JSON.stringify(body) }); }
